# Generated by Django 3.2.11 on 2022-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product_price',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
